name: 'Setup Flutter and Rust Environment'
description: 'è®¾ç½® Flutter å’Œ Rust å¼€å‘çŽ¯å¢ƒçš„å¯å¤ç”¨ Action'

inputs:
  flutter-version:
    description: 'Flutter ç‰ˆæœ¬'
    required: false
    default: '3.38.4'
  
  platform:
    description: 'ç›®æ ‡å¹³å° (linux, windows, android)'
    required: true
  
  rust-targets:
    description: 'Rust ç›®æ ‡æž¶æž„ (ç”¨ç©ºæ ¼åˆ†éš”)'
    required: false
    default: ''

outputs:
  flutter-path:
    description: 'Flutter å®‰è£…è·¯å¾„'
    value: ${{ steps.flutter-setup.outputs.flutter-path }}

runs:
  using: 'composite'
  steps:
    - name: ðŸ¦€ è®¾ç½® Rust å·¥å…·é“¾ 1.89.0
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          powershell -Command "& '${{ github.workspace }}\scripts\install_rust.ps1'"
        else
          chmod +x ${{ github.workspace }}/scripts/install_rust.sh
          ${{ github.workspace }}/scripts/install_rust.sh
        fi

    - name: ðŸŽ¯ é…ç½® Rust ç›®æ ‡æž¶æž„
      if: inputs.rust-targets != ''
      shell: bash
      run: |
        for target in ${{ inputs.rust-targets }}; do
          rustup target add $target
        done

    - name: ðŸ“¦ å®‰è£…ç³»ç»Ÿä¾èµ– (Android)
      if: inputs.platform == 'android'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libc6-dev
        sudo apt-get install -y libc6-dev-armhf-cross gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
        sudo apt-get install -y clang llvm libclang-dev
        sudo apt-get install -y libc-dev
        sudo apt-get install -y libc6-dev-i386 gcc-multilib g++-multilib
        sudo apt-get install -y protobuf-compiler

    - name: ðŸ“¦ å®‰è£…ç³»ç»Ÿä¾èµ– (Linux)
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build libgtk-3-dev
        sudo apt-get install -y clang cmake pkg-config libcurl4-openssl-dev
        sudo apt-get install -y protobuf-compiler
        sudo apt-get install -y libayatana-appindicator3-dev
        sudo apt-get install -y patchelf ruby-dev fuse libfuse2
        sudo gem install --no-document fpm

    - name: â˜• è®¾ç½® JDK 17 (Android)
      if: inputs.platform == 'android'
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: ðŸ¤– è®¾ç½® Android SDK
      if: inputs.platform == 'android'
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '28.2.13676358'
        cmake-version: '3.18.1'

    - name: ðŸ¦ å®‰è£… Flutter
      id: flutter-setup
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "æ­£åœ¨å…‹éš†Flutterç¨³å®šåˆ†æ”¯..."
          git clone https://github.com/flutter/flutter.git --branch ${{ inputs.flutter-version }} $GITHUB_WORKSPACE/flutter --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          echo "flutter-path=$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_OUTPUT
          echo "Flutterç‰ˆæœ¬éªŒè¯ï¼š"
          $GITHUB_WORKSPACE/flutter/bin/flutter.bat --version
        else
          git clone https://github.com/flutter/flutter.git --branch ${{ inputs.flutter-version }} $HOME/flutter --depth 1
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          echo "flutter-path=$HOME/flutter/bin" >> $GITHUB_OUTPUT
          export PATH="$HOME/flutter/bin:$PATH"
          chmod +x $HOME/flutter/bin/flutter
          flutter --version
        fi

    - name: ðŸŽ¯ å¯ç”¨å¹³å°æ”¯æŒ
      shell: bash
      run: |
        if [[ "${{ inputs.platform }}" == "linux" ]]; then
          flutter config --enable-linux-desktop
          flutter create --platforms=linux .
        fi

    - name: ðŸ“š å®‰è£… Flutter ä¾èµ–
      shell: bash
      run: flutter pub get

    - name: ðŸ¦€ å®‰è£… cargo-ndk (Android)
      if: inputs.platform == 'android'
      shell: bash
      run: cargo install cargo-ndk

    - name: ðŸ”§ è®¾ç½® bindgen çŽ¯å¢ƒå˜é‡ (Android)
      if: inputs.platform == 'android'
      shell: bash
      run: |
        echo "BINDGEN_EXTRA_CLANG_ARGS=-I/usr/include -I/usr/include/x86_64-linux-gnu" >> $GITHUB_ENV
        echo "LIBCLANG_PATH=/usr/lib/x86_64-linux-gnu" >> $GITHUB_ENV