// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../magic_wall.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `IS_RUNNING`, `MAGIC_WALL_RULES`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

Future<void> startMagicWall() =>
    RustLib.instance.api.crateApiMagicWallWindowsImplStartMagicWall();

Future<void> stopMagicWall() =>
    RustLib.instance.api.crateApiMagicWallWindowsImplStopMagicWall();

Future<void> addMagicWallRule({required MagicWallRule rule}) => RustLib
    .instance
    .api
    .crateApiMagicWallWindowsImplAddMagicWallRule(rule: rule);

Future<void> removeMagicWallRule({required String ruleId}) => RustLib
    .instance
    .api
    .crateApiMagicWallWindowsImplRemoveMagicWallRule(ruleId: ruleId);

Future<void> updateMagicWallRule({required MagicWallRule rule}) => RustLib
    .instance
    .api
    .crateApiMagicWallWindowsImplUpdateMagicWallRule(rule: rule);

Future<MagicWallStatus> getMagicWallStatus() =>
    RustLib.instance.api.crateApiMagicWallWindowsImplGetMagicWallStatus();
