// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_binding_request_with_change`, `create_binding_request`, `detect_nat_type_rfc5780`, `generate_transaction_id`, `parse_address_attribute`, `parse_stun_response`, `test_udp_ipv4`, `test_udp_ipv6_nat`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`

/// 综合网络测试 - Flutter 友好的 API
/// NAT 类型检测（RFC 5780）
Future<NetworkTestResult> testNetworkConnectivity({
  required String stunServer,
}) => RustLib.instance.api.crateApiNatTestTestNetworkConnectivity(
  stunServer: stunServer,
);

/// 检测 IPv4 NAT 类型（向后兼容）
Future<String> detectNatType({required String stunServer}) =>
    RustLib.instance.api.crateApiNatTestDetectNatType(stunServer: stunServer);

enum NatType {
  openInternet,
  fullCone,
  restrictedCone,
  portRestrictedCone,
  symmetric,
  symmetricUdpFirewall,
  blocked,
  unknown;

  Future<String> getDescription() =>
      RustLib.instance.api.crateApiNatTestNatTypeGetDescription(that: this);
}

/// NAT 检测结果（RFC 5780）
class NetworkTestResult {
  final String natTypeV4;
  final String natTypeV6;
  final PlatformInt64 ipv4Latency;
  final PlatformInt64 ipv6Latency;

  const NetworkTestResult({
    required this.natTypeV4,
    required this.natTypeV6,
    required this.ipv4Latency,
    required this.ipv6Latency,
  });

  @override
  int get hashCode =>
      natTypeV4.hashCode ^
      natTypeV6.hashCode ^
      ipv4Latency.hashCode ^
      ipv6Latency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkTestResult &&
          runtimeType == other.runtimeType &&
          natTypeV4 == other.natTypeV4 &&
          natTypeV6 == other.natTypeV6 &&
          ipv4Latency == other.ipv4Latency &&
          ipv6Latency == other.ipv6Latency;
}
