name: 🪟 构建 Windows 应用

on:
  workflow_dispatch:
  push:  # 每次 push 到仓库时触发
    tags:
      - 'v*'   # 指定触发分支

jobs:
  build:
    runs-on: windows-latest

    # 调整 GITHUB_TOKEN 的权限
    permissions:
      contents: write  # 允许写入仓库内容（上传文件）
      packages: write
      
    steps:
      - name: 🛠️ 检出代码仓库
        uses: actions/checkout@v4

      # 安装 Rust
      - name: 🦀 安装 Rust 1.89.0
        run: |
          choco install rust --version 1.89.0 -y
          echo "Rust 版本验证："
          rustc --version
        shell: pwsh

      # 安装 Flutter
      - name: 🐦 安装 Flutter
        run: |
          echo "正在克隆 Flutter 稳定分支..."
          git clone https://github.com/flutter/flutter.git --branch 3.29.3 $env:GITHUB_WORKSPACE/flutter --depth 1

          echo "正在将 Flutter 添加到 PATH..."
          echo "$env:GITHUB_WORKSPACE/flutter/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          echo "Flutter 版本验证："
          & "$env:GITHUB_WORKSPACE/flutter/bin/flutter.bat" --version
        shell: pwsh

      # 安装构建工具
      - name: 🛠️ 安装构建工具
        run: |
          choco install ninja cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          echo "CMake 版本验证："
          cmake --version
        shell: pwsh

      # 设置环境变量
      - name: ⚙️ 设置环境变量
        run: |
          echo "CARGO_NET_GIT_FETCH_WITH_CLI=true" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "RUST_BACKTRACE=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        shell: pwsh

      # 安装 Flutter 依赖
      - name: 📦 安装 Flutter 依赖
        run: |
          echo "正在获取 Flutter 依赖..."
          flutter pub get
          echo "Flutter 依赖安装完成！"
        shell: pwsh

      # 编译 Flutter Windows 应用
      - name: 🛠️ 编译 Flutter Windows 应用
        run: |
          echo "正在编译 Flutter Windows Release 版本..."
          flutter build windows --release --verbose
          echo "Flutter Windows Release 编译完成！"
        shell: pwsh

      # 复制 DLL 文件到输出目录
      - name: 📂 复制 DLL 文件到 Release 目录
        run: |
          echo "正在复制 DLL 文件到 Release 目录..."
          $dllSourceDir = "$env:GITHUB_WORKSPACE\dlls"
          $releaseDir = "$env:GITHUB_WORKSPACE\build\windows\x64\runner\Release"
          Copy-Item -Path "$dllSourceDir\*" -Destination $releaseDir -Recurse -Force
          echo "DLL 文件已复制到 $releaseDir！"

      # 压缩 Release 目录
      - name: 📦 压缩 Release 目录
        run: |
          echo "正在压缩 Release 目录..."
          $releaseDir = "$env:GITHUB_WORKSPACE\build\windows\x64\runner\Release"
          $zipFile = "$env:GITHUB_WORKSPACE\astral-windows-x64-zip.zip"
          Compress-Archive -Path "$releaseDir\*" -DestinationPath $zipFile -Force
          echo "Release 目录已压缩为 $zipFile！"

      # 上传压缩后的 Release 目录作为 Artifact
      - name: 📤 上传压缩后的 Release 目录
        uses: actions/upload-artifact@v4
        with:
          name: astral-windows-x64-zip
          path: ${{ github.workspace }}/astral-windows-x64-zip.zip
